<!DOCTYPE html>
<html>
<head>
		<meta charset="utf-8">
		<title>
			Seinheit
			<?php if(Navigation::getTitle()): ?>
				- <?php echo Navigation::getTitle(); ?>
			<?php endif ?>
		</title>
		<link href='http://fonts.googleapis.com/css?family=Amaranth' rel='stylesheet' type='text/css'>
		<link rel="stylesheet" type="text/css" href="<?php echo $this->base ?>/style/main.css" />
		<link rel="shortcut icon" href="<?php echo $this->base ?>/img/favicon.ico" type="image/x-icon" />
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<meta name="Description" content="" />
		<meta name="keywords" content="" />
</head>
<body>

<div id="container">
	<header>

		<?php if(Access::isLogged()): ?>
			<ul id="adminNavigation">
				<li>Admin Bereich</li>
				<li><a href="<?php echo $this->base ?>/adminNavigation">Navigationen</a></li>
				<li><a href="<?php echo $this->base ?>/adminPage">Pages</a></li>
				<li><a href="<?php echo $this->base ?>/admin/logout">Ausloggen</a></li>
			</ul>
		<?php endif ?>

		<?php if($this->notices): ?>
			<ul class="notices">
				<?php foreach($this->notices as $notice): ?>
				<li><?php echo $notice ?></li>
				<?php endforeach ?>
			</ul>
		<?php endif ?>

		<nav>
		    <a id="logo" href="<?php echo $this->base ?>/"><img src="<?php echo $this->base ?>/img/logo.png" alt="SEINHEIT logo"/></a>

			<ul id="navi">
			<?php foreach($this->mainNavigationItems as $item): ?>
				<li <?php if($item['id'] == $this->activeMenuItem) echo 'class="active"'?>>
					<a href="<?php echo $this->base ?>/<?php echo $item['controller'] ?>/<?php echo $item['action'] ?>"><?php echo $item['name'] ?></a>
				</li>
			<?php endforeach ?>
			</ul>
		</nav>

	</header>

	<article id="stage">

    	<?php if($this->headerImage): ?>
    		<img id="header_image" src="<?php echo $this-headerImage ?>" alt="">
    	<?php endif ?>

		<h1><?php echo Navigation::getTitle(); ?></h1>
		<?php if(Navigation::getSubtitle()): ?>
			<h2><?php echo Navigation::getSubtitle(); ?></h2>
		<?php endif ?>

		<div id="content">
			<?php echo $this->stageContent ?>
		</div>

	</article>

</div>
</body>
</html>