<html>
<head>
        <title>Swiss Didgeridoo Artwork</title>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->base ?>/style/main.css" />
        <link rel="shortcut icon" href="<?php echo $this->base ?>/img/leafs/favicon.ico" type="image/x-icon" /> 
</head>
<body id="index">
<a href="<?php echo $this->base ?>/page/home" title="Klick!" alt="Willkommensbild">
        <img src="<?php echo $this->base ?>/img/leafs/index.png" />
</a>
</body>
</html>