<html>
<head>
        <title>Swiss Didgeridoo Artwork - Schweizer Holz Didgeridoo bester Qualit&auml;t</title>
        <link rel="stylesheet" type="text/css" href="/style/main.css" />
        <link rel="shortcut icon" href="/img/leafs/favicon.ico" type="image/x-icon" />
        <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
        <meta name="Description" content="Bei uns findest du alles rund ums Didgeridoo - Qualitäts Instrumente aus einheimischen Hölzern - Taschen - Mundstücke - Musik - Konzertkalender - Unterricht -Therapie - Clapstick - Trommel Reparaturen - Diverse Links" />
        <meta name="keywords" content="Didgeridoo, Didjeridoo, Yidaki, Clapstick, Mundstück, Holzblasinstrument, Australisches Instrument, Didgeridoo Reparaturen, Didgeridoo Konzert, Trommel Reparaturen, Didgeridoo Unterricht, Zirkularatmung, Rhythmus Didgeridoo" />
        </head>
<body id="index">
<a href="<?php echo $this->base ?>/page/home" title="Klick!" alt="Willkommensbild">
        <img src="<?php echo $this->base ?>/img/leafs/index.png" />
</a>
</body>
</html>