<div id="admin">
<h3>Page bearbeiten</h3>

<form action="<?php echo $this->base ?>/adminPage/save"method="post">
        <input type="hidden" name="id" value="<?php echo $this->page['id'] ?>" />
        <dl>
                <dt>Aktiv</dt>
                <dd>
                        <input type="checkbox" name="active" <?php if($this->page['active']) echo 'checked="checked"' ?> />
                </dd>
        </dl>
        <dl>
                <dt>Titel</dt>
                <dd>
                        <input class="textfield" type="text" name="title" value="<?php echo $this->page['title'] ?>"/>
                </dd>
        </dl>
        <dl>
                <dt>Untertitel</dt>
                <dd>
                        <input class="textfield" type="text" name="subtitle" value="<?php echo $this->page['subtitle'] ?>"/>
                </dd>
        </dl>
        <dl>
                <dt>Url</dt>
                <dd>
                        <input class="textfield" type="text" name="url" value="<?php echo $this->page['url'] ?>"/>
                </dd>
        </dl>        
        <dl>
                <dt>Headerbild</dt>
                <dd>
                        <input class="textfield" type="text" name="header_image" value="<?php echo $this->page['header_image'] ?>" /> 
                        <a onclick="alert('choose');">Auswählen</a> | <a onclick="alert('upload');">Hochladen</a>
                </dd>
        </dl>
        <dl>
                <dt>Inhalt</dt>
                <dd>
                        <!-- Gets replaced with TinyMCE, remember HTML in a textarea should be encoded -->
                        <div>
                                <textarea id="content" name="content" rows="15" cols="80" style="width: 500px"><?php echo htmlentities($this->page['content']) ?></textarea>
                        </div>

                </dd>
        </dl>
        <p>
                <input type="submit" name="save" value="speichern" />
        </p>
</form>
</div>