<div id="admin">
<h3>Page bearbeiten</h3>

<!-- TinyMCE -->
<script type="text/javascript" src="<?php echo $this->base ?>/scripts/tiny_mce/tiny_mce.js"></script>
<script type="text/javascript">
        tinyMCE.init({
                // General options
                language : "de",
                mode : "textareas",
                theme : "advanced",
                plugins : "pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template,wordcount,advlist,autosave",

                // Theme options
                theme_advanced_buttons1 : "save,newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,styleselect,formatselect,fontselect,fontsizeselect",
                theme_advanced_buttons2 : "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,preview,|,forecolor,backcolor",
                theme_advanced_buttons3 : "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,charmap,emotions,iespell,media,advhr,|,print,|,ltr,rtl,|,fullscreen",
                theme_advanced_buttons4 : "insertlayer,moveforward,movebackward,absolute,|,styleprops,|,cite,abbr,acronym,del,ins,attribs,|,visualchars,nonbreaking,template,pagebreak,restoredraft",
                theme_advanced_toolbar_location : "top",
                theme_advanced_toolbar_align : "left",
                theme_advanced_statusbar_location : "bottom",
                theme_advanced_resizing : true,

                // Example content CSS (should be your site CSS)
                content_css : "<?php echo $this->base ?>/style/tiny.css",

                // Drop lists for link/image/media/template dialogs
                template_external_list_url : "lists/template_list.js",
                external_link_list_url : "lists/link_list.js",
                external_image_list_url : "lists/image_list.js",
                media_external_list_url : "lists/media_list.js",

                // Style formats
                style_formats : [
                        {title : 'Bold text', inline : 'b'},
                        {title : 'Red text', inline : 'span', styles : {color : '#ff0000'}},
                        {title : 'Red header', block : 'h1', styles : {color : '#ff0000'}},
                        {title : 'Example 1', inline : 'span', classes : 'example1'},
                        {title : 'Example 2', inline : 'span', classes : 'example2'},
                        {title : 'Table styles'},
                        {title : 'Table row 1', selector : 'tr', classes : 'tablerow1'}
                ],

                // Replace values for the template plugin
                template_replace_values : {
                        username : "Some User",
                        staffid : "991234"
                }
        });
</script>
<!-- /TinyMCE -->

<form action="<?php echo $this->base ?>/adminPage/save"method="post">
        <input type="hidden" name="id" value="<?php echo $this->page['id'] ?>" />
        <dl>
                <dt>Aktiv</dt>
                <dd>
                        <input type="checkbox" name="active" <?php if($this->page['active']) echo 'checked="checked"' ?> />
                </dd>
        </dl>
        <dl>
                <dt>Titel</dt>
                <dd>
                        <input class="textfield" type="text" name="title" value="<?php echo $this->page['title'] ?>"/>
                </dd>
        </dl>
        <dl>
                <dt>Untertitel</dt>
                <dd>
                        <input class="textfield" type="text" name="subtitle" value="<?php echo $this->page['subtitle'] ?>"/>
                </dd>
        </dl>
        <dl>
                <dt>Url</dt>
                <dd>
                        <input class="textfield" type="text" name="url" value="<?php echo $this->page['url'] ?>"/>
                </dd>
        </dl>        
        <dl>
                <dt>Header&nbsp;Bild</dt>
                <dd>
                        <input class="textfield" type="text" name="header_image" value="<?php echo $this->page['header_image'] ?>"/> 
                        <a href="javascript: void(0);" onclick="window.open('/adminPage/image/type/header', 'fenster1', 'width=600,height=400,status=yes,scrollbars=yes,resizable=yes');">Auswählen</a>
                </dd>
        </dl>
        <dl>
                <dt>Inhalt</dt>
                <dd>
                        <!-- Gets replaced with TinyMCE, remember HTML in a textarea should be encoded -->
                        <div>
                                <textarea id="content" name="content" rows="15" cols="80" style="width: 500px"><?php echo htmlentities($this->page['content']) ?></textarea>
                        </div>

                </dd>
        </dl>
        <p>
                <input type="submit" name="save" value="speichern" />
        </p>
</form>
</div>