<div id="admin">
<h3>Page Übersicht</h3>
<table>
<tr>
	<th>
		Aktiv
	</th>
	<th>
		Titel
	</th>
	<th>
		Untertitel
	</th>
	<th>
		Url
	</th>
	<th colspan="3">
		&nbsp;
	</th>
</tr>

<?php foreach($this->pages as $page): ?>
<tr>
	<td>
		<?php if($page['active']) echo 'Ja'; else echo 'Nein'; ?>
	</td>
	<td>
		<?php echo $page['title'] ?>
	</td>
	<td>
		<?php echo $page['subtitle'] ?>
	</td>
	<td>
		<?php echo $page['url'] ?>
	</td>
	<td>
		<a href="<?php echo $this->base ?>/adminPage/delete/pageId/<?php echo $page['id'] ?>">
			<img src="<?php echo $this->base ?>/img/leafs/delete.png" alt="Löschen" title="Löschen" />
		</a>
	</td>
	<td>
		<a href="<?php echo $this->base ?>/adminPage/edit/pageId/<?php echo $page['id'] ?>">
			<img src="<?php echo $this->base ?>/img/leafs/change.png" alt="Ändern" title="Ändern" />
		</a>
	</td>
	<td>
		<a href="<?php echo $this->base ?>/page/<?php echo $page['url'] ?>/preview">
			<img src="<?php echo $this->base ?>/img/leafs/preview.png" alt="Vorschau" title="Vorschau" />
		</a>
	</td>
</tr>
<?php endforeach ?>
</table>
<p>
	<a href="<?php echo $this->base ?>/adminPage/edit">Neue Seite anlegen</a>
</p>
</div>